package healthband

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/insajin/autopus-adk/pkg/lore"
)

func commitInput() PatchCommitInput {
	z := 4.126
	return PatchCommitInput{
		Series: "ci.failure_rate:CI", EpisodeID: "e1042", Tier: 3, Z: &z, BSID: "BS-BAND-001",
		Lore: lore.LoreConfig{RequiredTrailers: []string{"Constraint", "Tested"}, ForbiddenTrailers: []string{"Co-Authored-By"}},
	}
}

func TestBandSlug_KeyRule(t *testing.T) {
	t.Parallel()
	cases := map[string]string{
		"ci.failure_rate:CI":     "ci-failure-rate-ci",
		"e1042":                  "e1042",
		"--Canary  +#x--":        "canary-x",
		"":                       "",
		strings.Repeat("ab", 30): strings.Repeat("ab", 20),
		"Ünïcode:Name":           "n-code-name",
	}
	for raw, want := range cases {
		assert.Equal(t, want, BandSlug(raw), raw)
	}
}

func TestPatchCommitMessage_FinalMessage_ExactBytesAndValid(t *testing.T) {
	t.Parallel()
	in := commitInput()
	in.PatchModel = "claude-opus-5-5"
	message, code := PatchCommitMessage(in)
	require.Empty(t, code)
	want := "fix(band): ci-failure-rate-ci anomaly local patch (e1042)\n\n" +
		"Tier: 3\nz: 4.13\nBS: BS-BAND-001\nPatch model: claude-opus-5-5\n\n" +
		"Constraint: generated by auto react band; local patch needs human review\n" +
		"Rejected: write-capable agent; read-only proposal only\n" +
		"Confidence: low\n" +
		"Directive: review the patch file before running anything\n" +
		"Tested: none; nothing was run\n" +
		"Related: BS-BAND-001\n\n" +
		"🐙 Autopus <noreply@autopus.co>\n"
	assert.Equal(t, want, message)
	assert.Empty(t, lore.Validate(message, in.Lore))
}

func TestPatchCommitMessage_Draft_HasNoPatchModelLine(t *testing.T) {
	t.Parallel()
	message, code := PatchCommitMessage(commitInput())
	require.Empty(t, code)
	assert.NotContains(t, message, "Patch model:")
	assert.Contains(t, message, "BS: BS-BAND-001\n\nConstraint:")
}

func TestPatchCommitMessage_KoreanSubject(t *testing.T) {
	t.Parallel()
	in := commitInput()
	in.Language = "ko"
	message, code := PatchCommitMessage(in)
	require.Empty(t, code)
	assert.True(t, strings.HasPrefix(message, "fix(band): ci-failure-rate-ci 이상 대응 로컬 패치 (e1042)\n\n"), message)
}

func TestPatchCommitMessage_AbsentZ(t *testing.T) {
	t.Parallel()
	in := commitInput()
	in.Z = nil
	message, code := PatchCommitMessage(in)
	require.Empty(t, code)
	assert.Contains(t, message, "\nz: n/a\n")
}

func TestPatchCommitMessage_Refusals(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name             string
		required, forbid []string
		wantCode         string
	}{
		{"required Related is not one lore.Validate recognizes", []string{"Constraint", "Related"}, nil, "lore_unsupported_required:Related"},
		{"required Scope-risk", []string{"Scope-risk"}, nil, "lore_unsupported_required:Scope-risk"},
		{"lowercase spelling is unsupported", []string{"tested"}, nil, "lore_unsupported_required:tested"},
		{"hostile trailer name is spelled safely", []string{"X\n: y"}, nil, "lore_unsupported_required:X___y"},
		{"forbidden Related", nil, []string{"Related"}, "lore_rejected"},
		{"forbidden Confidence, case-insensitive", nil, []string{"confidence"}, "lore_rejected"},
		{"all five supported", []string{"Constraint", "Rejected", "Confidence", "Directive", "Tested"}, nil, ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			in := commitInput()
			in.Lore = lore.LoreConfig{RequiredTrailers: tc.required, ForbiddenTrailers: tc.forbid}
			message, code := PatchCommitMessage(in)
			assert.Equal(t, tc.wantCode, code)
			if tc.wantCode != "" {
				assert.Empty(t, message)
			}
		})
	}
}

func TestPatchCommitMessage_InvalidInput_Rejected(t *testing.T) {
	t.Parallel()
	for _, mutate := range []func(*PatchCommitInput){
		func(in *PatchCommitInput) { in.BSID = "" },
		func(in *PatchCommitInput) { in.BSID = "BS-BAND-001\nRelated: x" },
		func(in *PatchCommitInput) { in.EpisodeID = "" },
		func(in *PatchCommitInput) { in.Series = "###" },
		func(in *PatchCommitInput) { in.PatchModel = "claude\nConfidence: high" },
	} {
		in := commitInput()
		mutate(&in)
		message, code := PatchCommitMessage(in)
		assert.Equal(t, LoreRejected, code)
		assert.Empty(t, message)
	}
}
