package healthband

import (
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/insajin/autopus-adk/pkg/lore"
)

// Commit message of a band local patch (SPEC-SIGMABAND-002 REQ-06, Local
// Patch Flow steps 5–6). The message is built with lore.BuildCommit and
// validated with lore.Validate in-process, never by a commit-msg hook: step
// 5 validates the draft before the provider call, so a configuration that
// cannot take the band commit stops early, and step 6 validates the final
// message, which adds the body line `Patch model: <init model>`. The -F file
// is the BuildCommit output plus one newline, and `git commit
// --cleanup=verbatim` stores exactly those bytes.

// Commit message codes. A required trailer that lore.Validate cannot see
// gives LoreUnsupportedRequiredPrefix followed by its name.
const (
	LoreUnsupportedRequiredPrefix = "lore_unsupported_required:"
	LoreRejected                  = "lore_rejected"
)

// Fixed trailer values of every band commit (Local Patch Flow, commit
// message); Related always names the BS.
const (
	bandCommitConstraint = "generated by auto react band; local patch needs human review"
	bandCommitRejected   = "write-capable agent; read-only proposal only"
	bandCommitConfidence = "low"
	bandCommitDirective  = "review the patch file before running anything"
	bandCommitTested     = "none; nothing was run"
	bandSlugMaxBytes     = 40
	loreTrailerNameBytes = 64
)

// loreValidatedTrailers are the only trailers that lore.Validate's required
// check recognizes (pkg/lore query.go hasField); any other required trailer
// would fail every band message, so step 5 names it instead.
var loreValidatedTrailers = []string{"Constraint", "Rejected", "Confidence", "Directive", "Tested"}

var (
	bandCommitBSPattern    = regexp.MustCompile(`^[A-Za-z0-9._-]{1,64}$`)
	bandCommitModelPattern = regexp.MustCompile(`^[A-Za-z0-9._:/@-]{0,128}$`)
)

// PatchCommitInput is what the band commit message names.
type PatchCommitInput struct {
	Series    string   // series ID; the subject names its slug
	EpisodeID string   // episode ID; the subject names its slug
	Tier      int      // tier of the evaluation that opened the episode
	Z         *float64 // z of that evaluation; nil when absent
	BSID      string   // BS of the diagnosis; also the Related trailer
	// Language is the commit-message language; "ko" gives the Korean subject.
	Language string
	// PatchModel is the init model of the patch request; "" builds the
	// step-5 draft without the Patch model line.
	PatchModel string
	// Lore holds the configured required and forbidden trailers.
	Lore lore.LoreConfig
}

// BandSlug is the slug rule of the local patch key (SPEC-SIGMABAND-002
// `<key>` definition): lowercase, every run of characters outside [a-z0-9]
// replaced by one "-", trimmed of "-", and cut to 40 bytes. The commit
// subject and the key share it.
func BandSlug(s string) string {
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(s) {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			if dash && b.Len() > 0 {
				b.WriteByte('-')
			}
			dash = false
			b.WriteRune(r)
			continue
		}
		dash = true
	}
	slug := b.String()
	if len(slug) > bandSlugMaxBytes {
		slug = slug[:bandSlugMaxBytes]
	}
	return slug
}

// PatchCommitMessage returns the -F file bytes of the band commit, or ""
// and the code that stops the flow: lore_unsupported_required:<trailer> for
// a required trailer outside the five that lore.Validate recognizes, and
// lore_rejected for a message that lore.Validate refuses or an input that
// could put text outside its line into the message.
func PatchCommitMessage(in PatchCommitInput) (string, string) {
	for _, required := range in.Lore.RequiredTrailers {
		if !slices.Contains(loreValidatedTrailers, required) {
			return "", LoreUnsupportedRequiredPrefix + loreTrailerName(required)
		}
	}
	seriesSlug, episodeSlug := BandSlug(in.Series), BandSlug(in.EpisodeID)
	if seriesSlug == "" || episodeSlug == "" || !bandCommitBSPattern.MatchString(in.BSID) ||
		!bandCommitModelPattern.MatchString(in.PatchModel) {
		return "", LoreRejected
	}
	subject := "fix(band): " + seriesSlug + " anomaly local patch (" + episodeSlug + ")"
	if in.Language == "ko" {
		subject = "fix(band): " + seriesSlug + " 이상 대응 로컬 패치 (" + episodeSlug + ")"
	}
	z := "n/a"
	if in.Z != nil {
		z = strconv.FormatFloat(*in.Z, 'f', 2, 64)
	}
	body := []string{"Tier: " + strconv.Itoa(in.Tier), "z: " + z, "BS: " + in.BSID}
	if in.PatchModel != "" {
		body = append(body, "Patch model: "+in.PatchModel)
	}
	entry := &lore.LoreEntry{
		Constraint: bandCommitConstraint, Rejected: bandCommitRejected, Confidence: bandCommitConfidence,
		Directive: bandCommitDirective, Tested: bandCommitTested, Related: in.BSID,
	}
	built, err := lore.BuildCommit(entry, subject+"\n\n"+strings.Join(body, "\n"))
	if err != nil {
		return "", LoreRejected
	}
	message := built + "\n"
	if len(lore.Validate(message, in.Lore)) > 0 {
		return "", LoreRejected
	}
	return message, ""
}

// loreTrailerName spells a configured trailer name for a code: every byte
// outside [A-Za-z0-9-] as "_", at most 64 bytes, so no configuration text
// can put a control character into a record or the run output.
func loreTrailerName(name string) string {
	safe := []byte(name)
	for i, c := range safe {
		if !(c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '-') {
			safe[i] = '_'
		}
	}
	return string(safe[:min(len(safe), loreTrailerNameBytes)])
}
