'use strict';
// Read-only discovery crawler generated by `auto qa discover` (SPEC-QALOOP-001 REQ-17).
//
// The only navigation is page.goto on same-origin links; the crawler never
// interacts with a page beyond reading it. What it records is what the pages
// show today, so a scenario built from it is a regression baseline, not a
// correctness proof.
//
// Usage: node autopus-discover.cjs <origin> [maxPages]
// Prints one qamesh.discover.v1 JSON document on stdout.

const SCHEMA_VERSION = 'qamesh.discover.v1';
const PLAYWRIGHT_MISSING_EXIT = 3;
const USAGE_EXIT = 2;
const MAX_HEADINGS = 10;
const MAX_HEADING_CHARS = 120;
const NAVIGATION_TIMEOUT_MS = 30000;
const SETTLE_TIMEOUT_MS = 5000;
const LANDMARK_ROLES = ['main', 'navigation', 'banner', 'contentinfo', 'search'];
// A GET can still end a session or delete data, so links that look like one
// are never followed.
const UNSAFE_LINK = /(log-?out|sign-?out|log-?off|delete|destroy|remove|unsubscribe|revoke)/i;

function loadPlaywright() {
  const paths = [process.cwd()];
  for (const name of ['@playwright/test', 'playwright']) {
    try {
      return require(require.resolve(name, { paths }));
    } catch (err) {
      // Not installed under this name; try the next one.
    }
  }
  return null;
}

function parseOrigin(raw) {
  try {
    const url = new URL(raw);
    if (url.protocol === 'http:' || url.protocol === 'https:') return url.origin;
  } catch (err) {
    // Fall through to the usage error.
  }
  return null;
}

function sameOrigin(raw, base, origin) {
  let url;
  try {
    url = new URL(raw, base);
  } catch (err) {
    return null;
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return null;
  if (url.origin !== origin) return null;
  url.hash = '';
  if (UNSAFE_LINK.test(url.pathname + url.search)) return null;
  return url;
}

function squash(text, limit) {
  return String(text || '').replace(/\s+/g, ' ').trim().slice(0, limit);
}

// Headings come through getByRole, which skips hidden elements, so every
// recorded heading is one a visibility assertion can find.
async function headingsOf(page) {
  const headings = [];
  for (const level of [1, 2]) {
    for (const text of await page.getByRole('heading', { level }).allInnerTexts()) {
      const value = squash(text, MAX_HEADING_CHARS);
      if (value && !headings.includes(value) && headings.length < MAX_HEADINGS) headings.push(value);
    }
  }
  return headings;
}

async function landmarksOf(page) {
  const present = [];
  for (const role of LANDMARK_ROLES) {
    if ((await page.getByRole(role).count()) > 0) present.push(role);
  }
  return present;
}

// linksOf reads href values only; the callback has no side effect.
async function linksOf(page) {
  return page.locator('a[href]').evaluateAll((anchors) =>
    anchors.map((anchor) => (typeof anchor.href === 'string' ? anchor.href : anchor.getAttribute('href'))));
}

async function crawl(playwright, origin, maxPages) {
  const browser = await playwright.chromium.launch({ headless: true });
  const pages = [];
  try {
    const context = await browser.newContext();
    const page = await context.newPage();
    const start = new URL('/', origin).href;
    const queue = [start];
    const queued = new Set(queue);
    const recorded = new Set();
    while (queue.length > 0 && pages.length < maxPages) {
      const target = queue.shift();
      let response;
      try {
        response = await page.goto(target, { waitUntil: 'load', timeout: NAVIGATION_TIMEOUT_MS });
      } catch (err) {
        process.stderr.write(`autopus-discover: skipped ${target}: ${err.message}\n`);
        continue;
      }
      if (response && response.status() >= 400) continue;
      await page.waitForLoadState('networkidle', { timeout: SETTLE_TIMEOUT_MS }).catch(() => {});
      const landed = sameOrigin(page.url(), origin, origin);
      if (!landed) continue;
      const key = landed.pathname + landed.search;
      if (recorded.has(key)) continue;
      recorded.add(key);
      pages.push({
        path: key,
        title: squash(await page.title(), 1000),
        headings: await headingsOf(page),
        landmarks: await landmarksOf(page),
      });
      for (const href of await linksOf(page)) {
        const next = sameOrigin(href, page.url(), origin);
        if (!next || queued.has(next.href)) continue;
        queued.add(next.href);
        queue.push(next.href);
      }
    }
  } finally {
    await browser.close();
  }
  return pages;
}

async function main() {
  const origin = parseOrigin(process.argv[2] || process.env.AUTOPUS_DISCOVER_ORIGIN || '');
  if (!origin) {
    process.stderr.write('autopus-discover: pass an absolute http(s) origin\n');
    process.exit(USAGE_EXIT);
  }
  const requested = parseInt(process.argv[3] || process.env.AUTOPUS_DISCOVER_MAX_PAGES || '20', 10);
  const maxPages = Number.isFinite(requested) && requested > 0 ? requested : 20;
  const playwright = loadPlaywright();
  if (!playwright) {
    process.stderr.write(`autopus-discover: Playwright is not installed in ${process.cwd()}; ` +
      'run npm i -D @playwright/test && npx playwright install chromium\n');
    process.exit(PLAYWRIGHT_MISSING_EXIT);
  }
  const pages = await crawl(playwright, origin, maxPages);
  process.stdout.write(`${JSON.stringify({ schema_version: SCHEMA_VERSION, origin, pages })}\n`);
}

main().catch((err) => {
  process.stderr.write(`autopus-discover: ${err && err.stack ? err.stack : err}\n`);
  process.exit(1);
});
