package cli

import (
	"fmt"
	"io"
	"os"
	"time"

	"github.com/spf13/cobra"

	"github.com/insajin/autopus-adk/pkg/editguard"
)

const (
	// editGuardEnv set to editGuardOff in the agent CLI's environment turns the
	// guard off without regenerating hooks (REQ-EG-20).
	editGuardEnv = "AUTOPUS_EDIT_GUARD"
	editGuardOff = "off"
)

// editGuardClock decides lock expiry for `auto guard edit` and stamps the
// records of `auto fix`; tests pin it.
var editGuardClock = time.Now

// newGuardCmd builds the `auto guard` namespace of pre-tool hooks.
func newGuardCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:           "guard",
		Short:         "Pre-tool hooks that block unsafe file edits",
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	cmd.AddCommand(newGuardEditCmd())
	return cmd
}

// newGuardEditCmd builds the hook command a generated PreToolUse entry runs
// once per file-editing tool call (SPEC-EDITGUARD-001). It always exits 0: a
// deny is one stdout write in the platform's encoding, and an allow, a fault,
// an unknown platform, or an unparsable command line leaves stdout empty with
// at most one stderr line (REQ-EG-10, REQ-EG-11).
func newGuardEditCmd() *cobra.Command {
	var platform string
	cmd := &cobra.Command{
		Use:   "edit --platform <claude-code|opencode|codex>",
		Short: "Decide one file-editing tool call from the hook payload on stdin",
		// A command line generated by a newer release may carry flags or
		// arguments this binary does not know; they never fail the hook.
		Args:               cobra.ArbitraryArgs,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		SilenceUsage:       true,
		SilenceErrors:      true,
		// Shadows the root pre-run, so no config read can fail the hook.
		PersistentPreRunE: func(*cobra.Command, []string) error { return nil },
		RunE: func(cmd *cobra.Command, _ []string) error {
			guardEdit(platform, cmd.InOrStdin(), cmd.OutOrStdout(), cmd.ErrOrStderr())
			return nil
		},
	}
	cmd.Flags().StringVar(&platform, "platform", "", "hook payload dialect: claude-code, opencode, or codex")
	cmd.SetFlagErrorFunc(func(cmd *cobra.Command, _ error) error {
		if !editGuardDisabled() {
			fmt.Fprintln(cmd.ErrOrStderr(), "autopus edit-guard: allow (usage error)")
		}
		return nil
	})
	return cmd
}

// guardEdit runs one decision. The platform comes from the registered command
// line, never from the untrusted payload (REQ-EG-17).
func guardEdit(platform string, stdin io.Reader, stdout, stderr io.Writer) {
	if editGuardDisabled() {
		return
	}
	dialect, ok := editguard.DialectFor(platform)
	if !ok {
		fmt.Fprintln(stderr, "autopus edit-guard: allow (unknown platform)")
		return
	}
	editguard.Run(stdin, stdout, stderr, dialect, editguard.Options{Now: editGuardClock})
}

func editGuardDisabled() bool {
	return os.Getenv(editGuardEnv) == editGuardOff
}
