package scenario

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
)

// Options carries what the compiler cannot derive from the scenario itself.
type Options struct {
	// Origin is used when the scenario states none. Callers resolve it from the
	// Journey Pack's allowed_origins so a compiled spec can only ever navigate
	// somewhere the guard already permits.
	Origin string
	// FixtureImport is the specifier for the capture fixture, relative to the
	// emitted spec. The generated spec must import the project's own fixture:
	// importing @playwright/test directly would produce a spec that runs but
	// emits no capture evidence.
	FixtureImport string
}

// tsString renders a Go string as a TypeScript string literal. JSON encoding is
// used because a JSON string literal is a valid TS string literal and escapes
// quotes, backslashes, and control characters that would otherwise break out of
// the literal in generated source.
func tsString(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(encoded)
}

// tsRegex renders a substring match as a RegExp constructor argument. The value
// is regex-escaped first so scenario text containing metacharacters matches
// literally instead of becoming a pattern.
func tsRegex(value string) string {
	return "new RegExp(" + tsString(regexp.QuoteMeta(value)) + ")"
}

// Compile renders one scenario into a Playwright spec.
func Compile(s Scenario, opts Options) ([]byte, error) {
	body, _, err := CompileWithMap(s, opts)
	return body, err
}

// CompileWithMap renders a scenario plus the step map tying every emitted step
// line back to the scenario step it came from. Lines are counted while
// writing, never recovered by parsing the output, so the map cannot disagree
// with the file it describes. SpecPath is left for the caller to fill in.
func CompileWithMap(s Scenario, opts Options) ([]byte, StepMap, error) {
	if err := Validate(s); err != nil {
		return nil, StepMap{}, err
	}
	origin := strings.TrimRight(strings.TrimSpace(s.Origin), "/")
	if origin == "" {
		origin = strings.TrimRight(strings.TrimSpace(opts.Origin), "/")
	}
	if origin == "" {
		return nil, StepMap{}, invalid(s.Path, "qa_scenario_origin_unresolved",
			"no origin: set `origin:` in the scenario or declare allowed_origins on journey %q", s.Journey)
	}
	fixture := strings.TrimSpace(opts.FixtureImport)
	if fixture == "" {
		return nil, StepMap{}, invalid(s.Path, "qa_scenario_fixture_unresolved", "capture fixture import path is required")
	}

	out := &specWriter{}
	steps := newStepMap(s)
	writeHeader(out, s, fixture, origin)
	fmt.Fprintf(out, "test.describe(%s, () => {\n", tsString(s.ID+" "+describeTags(s)))
	for _, screen := range s.Screens {
		writeScreen(out, screen, &steps, s.IsV2())
	}
	out.WriteString("});\n")
	return []byte(out.String()), steps, nil
}

func writeHeader(out *specWriter, s Scenario, fixture, origin string) {
	fmt.Fprintf(out, "// Generated by 'auto qa scenario compile' from %s\n", DirRel+"/"+s.Path)
	out.WriteString("// Do not edit: regenerate after changing the scenario.\n//\n")
	if s.IsV2() {
		writeV2Notice(out, s)
	} else {
		out.WriteString("// Read-only by construction. The scenario schema cannot express click, fill,\n")
		out.WriteString("// press, or any other mutating action, so this spec cannot trip the\n")
		out.WriteString("// gui-explore forbidden-action guard.\n//\n")
	}
	fmt.Fprintf(out, "// Scenario: %s\n", sanitizeComment(s.Title))
	if s.IsV2() {
		fmt.Fprintf(out, "// Intent: %s\n", sanitizeComment(intentLine(s)))
	}
	if len(s.AcceptanceRef) > 0 {
		fmt.Fprintf(out, "// Acceptance: %s\n", sanitizeComment(strings.Join(s.AcceptanceRef, ", ")))
	}
	fmt.Fprintf(out, "\nimport { test, expect } from %s;\n\n", tsString(fixture))
	fmt.Fprintf(out, "const ORIGIN = %s;\n\n", tsString(origin))
	if usesBarePathURL(s) {
		out.WriteString(onPathHelper)
	}
	if usesValueEnv(s) {
		out.WriteString(missingEnvHelper)
	}
}

// sanitizeComment keeps authored prose from escaping its comment line. A newline
// would move the rest of the title into executable position.
func sanitizeComment(value string) string {
	replaced := strings.NewReplacer("\r", " ", "\n", " ", "*/", "* /").Replace(value)
	if len(replaced) > 200 {
		replaced = replaced[:200]
	}
	return strings.TrimSpace(replaced)
}

func writeScreen(out *specWriter, screen Screen, steps *StepMap, v2 bool) {
	fmt.Fprintf(out, "  test(%s, async ({ page }) => {\n", tsString(screen.ID))
	// The annotation is the only link between a declared screen and the capture
	// index step the screen_matrix oracle counts.
	fmt.Fprintf(out, "    test.info().annotations.push({ type: %s, description: %s });\n",
		tsString(ScreenAnnotation), tsString(screen.ID))
	steps.add(out.nextLine(), StepRef{Screen: screen.ID, Index: 0, Kind: StepKindGoto})
	fmt.Fprintf(out, "    await page.goto(ORIGIN + %s);\n", tsString(screen.Path))
	for index, step := range screen.Steps {
		steps.add(out.nextLine(), StepRef{
			Screen: screen.ID,
			Index:  index + 1,
			Kind:   step.Kind(),
			Ac:     strings.TrimSpace(step.Ac),
		})
		out.WriteString("    " + renderStep(step, v2) + "\n")
	}
	out.WriteString("  });\n")
}

func renderStep(step Step, v2 bool) string {
	if step.Action() != "" {
		return renderAction(step, v2)
	}
	switch {
	case strings.TrimSpace(step.ExpectTitle) != "":
		return "await expect(page).toHaveTitle(" + tsRegex(step.ExpectTitle) + ");"
	case strings.TrimSpace(step.ExpectURL) != "":
		return "await expect(page).toHaveURL(" + urlTarget(step.ExpectURL, v2) + ");"
	case strings.TrimSpace(step.ExpectText) != "":
		// .first() keeps a repeated string from failing Playwright strict mode,
		// which would report a locator error instead of the missing text.
		return "await expect(page.getByText(" + tsRegex(step.ExpectText) + ").first()).toBeVisible();"
	case step.ExpectRole != nil:
		return "await expect(" + roleLocator(step.ExpectRole.Role, step.ExpectRole.Name, step.ExpectRole.Exact) + ".first()).toBeVisible();"
	case step.ExpectCount != nil:
		return fmt.Sprintf("await expect(%s).toHaveCount(%d);",
			roleLocator(step.ExpectCount.Role, step.ExpectCount.Name, false), step.ExpectCount.Count)
	}
	// Unreachable: Validate rejects a step with no assertion.
	return "// unsupported step"
}

func roleLocator(role, name string, exact bool) string {
	normalized := strings.ToLower(strings.TrimSpace(role))
	if strings.TrimSpace(name) == "" {
		return "page.getByRole(" + tsString(normalized) + ")"
	}
	options := "{ name: " + tsString(name)
	if exact {
		options += ", exact: true"
	}
	options += " }"
	return "page.getByRole(" + tsString(normalized) + ", " + options + ")"
}

// ScreenMatrix projects the scenario set onto the journey.GUIScreenMatrixRow
// shape the Journey Pack declares, so `screen_matrix` and the compiled specs
// cannot drift apart. goto is the action every compiled screen performs.
//
// v2 actions are deliberately not listed. The capture fixture records only
// page-level calls (page.goto, page.click, ...), while compiled specs act
// through locators, so a required "click" would never be observed and the
// oracle would fail every journey for a gap in evidence, not in the product.
func ScreenMatrix(scenarios []Scenario, journeyID string) []map[string]any {
	rows := make([]map[string]any, 0)
	for _, s := range scenarios {
		if journeyID != "" && s.Journey != journeyID {
			continue
		}
		for _, screen := range s.Screens {
			rows = append(rows, map[string]any{
				"id":               screen.ID,
				"path":             screen.Path,
				"required_actions": []string{"goto"},
			})
		}
	}
	return rows
}
