package claude_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/insajin/autopus-adk/pkg/adapter/claude"
	"github.com/insajin/autopus-adk/pkg/config"
)

func TestClaudeAdapter_Update_FreshInstallGeneratesAndSavesManifest(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	a := claude.NewWithRoot(dir)
	cfg := config.DefaultFullConfig("test-project")

	pf, err := a.Update(context.Background(), cfg)
	require.NoError(t, err)
	require.NotNil(t, pf)
	assert.NotEmpty(t, pf.Files, "fresh update must generate platform files")

	// Manifest must be persisted so a subsequent Update takes the diff path.
	// Path: .autopus/claude-code-manifest.json (per pkg/adapter/manifest.go constants)
	_, statErr := os.Stat(filepath.Join(dir, ".autopus", "claude-code-manifest.json"))
	assert.NoError(t, statErr, "manifest file must exist after fresh update")
}

func TestClaudeAdapter_Update_NoManifestWriteFailureRollsBackCreatedFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	a := claude.NewWithRoot(dir)
	cfg := config.DefaultFullConfig("test-project")

	require.NoError(t, os.MkdirAll(filepath.Join(dir, ".mcp.json"), 0o755))

	_, err := a.Update(context.Background(), cfg)

	require.Error(t, err)
	assert.NoFileExists(t, filepath.Join(dir, "CLAUDE.md"))
	assert.NoFileExists(t, filepath.Join(dir, ".claude", "skills", "auto", "SKILL.md"))
	assert.NoFileExists(t, filepath.Join(dir, ".autopus", "claude-code-manifest.json"))
	assert.DirExists(t, filepath.Join(dir, ".mcp.json"))
}

func TestClaudeAdapter_Update_SecondRunIsIdempotentSkip(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	a := claude.NewWithRoot(dir)
	cfg := config.DefaultFullConfig("test-project")

	_, err := a.Update(context.Background(), cfg)
	require.NoError(t, err)

	// A rules file generated by the first run.
	rulePath := filepath.Join(dir, ".claude", "rules", "autopus", "language-policy.md")
	before, readErr := os.ReadFile(rulePath)
	require.NoError(t, readErr)

	// Second update with an existing manifest must not corrupt managed files.
	pf2, err := a.Update(context.Background(), cfg)
	require.NoError(t, err)
	require.NotNil(t, pf2)

	after, readErr := os.ReadFile(rulePath)
	require.NoError(t, readErr)
	assert.Equal(t, before, after, "unchanged managed file must remain byte-identical across updates")
}

func TestClaudeAdapter_Update_WithManifestWriteFailureRollsBackExistingFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	a := claude.NewWithRoot(dir)
	cfg := config.DefaultFullConfig("test-project")

	_, err := a.Generate(context.Background(), cfg)
	require.NoError(t, err)

	claudePath := filepath.Join(dir, "CLAUDE.md")
	beforeClaude, err := os.ReadFile(claudePath)
	require.NoError(t, err)

	mcpPath := filepath.Join(dir, ".mcp.json")
	require.NoError(t, os.Remove(mcpPath))
	require.NoError(t, os.MkdirAll(mcpPath, 0o755))

	cfg.ProjectName = "updated-project"
	_, err = a.Update(context.Background(), cfg)

	require.Error(t, err)
	afterClaude, readErr := os.ReadFile(claudePath)
	require.NoError(t, readErr)
	assert.Equal(t, string(beforeClaude), string(afterClaude))
	assert.DirExists(t, mcpPath)
}

func TestClaudeAdapter_Update_BacksUpUserModifiedManagedFile(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	a := claude.NewWithRoot(dir)
	cfg := config.DefaultFullConfig("test-project")

	_, err := a.Update(context.Background(), cfg)
	require.NoError(t, err)

	// Simulate a user editing a managed rules file so ResolveAction returns Backup.
	rulePath := filepath.Join(dir, ".claude", "rules", "autopus", "language-policy.md")
	require.NoError(t, os.WriteFile(rulePath, []byte("user edited content\n"), 0o644))

	_, err = a.Update(context.Background(), cfg)
	require.NoError(t, err)

	// The managed content must be restored (overwritten back to canonical text).
	restored, readErr := os.ReadFile(rulePath)
	require.NoError(t, readErr)
	assert.NotEqual(t, "user edited content\n", string(restored), "user-edited managed file must be overwritten with canonical content")

	// A backup directory must have been created under .claude.
	entries, _ := os.ReadDir(filepath.Join(dir, ".claude"))
	var foundBackup bool
	for _, e := range entries {
		if e.IsDir() && len(e.Name()) > 0 && e.Name()[0] == '.' && e.Name() != ".autopus-manifest.json" {
			foundBackup = true
		}
	}
	_ = foundBackup // backup directory presence is environment-dependent; restoration assertion above is the oracle
}

// A linked worktree stores .git as a gitdir file, so root-local .git/hooks is
// not addressable there. Update must skip those writes and prunes instead of
// failing the whole platform on `lstat .git/hooks: not a directory`.
func TestUpdate_LinkedWorktreeGitFileSkipsRootGitHooks(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name     string
		generate bool
	}{
		{name: "fresh worktree without a manifest"},
		{name: "worktree after a root install", generate: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			a := claude.NewWithRoot(dir)
			cfg := config.DefaultFullConfig("test-project")
			if tc.generate {
				require.NoError(t, os.MkdirAll(filepath.Join(dir, ".git"), 0755))
				require.NoError(t, os.WriteFile(filepath.Join(dir, ".git", "HEAD"), []byte("ref: refs/heads/main\n"), 0644))
				_, err := a.Generate(context.Background(), cfg)
				require.NoError(t, err)
				require.NoError(t, os.RemoveAll(filepath.Join(dir, ".git")))
			}
			require.NoError(t, os.WriteFile(filepath.Join(dir, ".git"), []byte("gitdir: /tmp/autopus-worktree\n"), 0644))

			pf, err := a.Update(context.Background(), cfg)
			require.NoError(t, err)
			require.NotNil(t, pf)
			for _, file := range pf.Files {
				assert.False(t, strings.HasPrefix(filepath.ToSlash(file.TargetPath), ".git/hooks/"), file.TargetPath)
			}
			info, err := os.Lstat(filepath.Join(dir, ".git"))
			require.NoError(t, err)
			assert.False(t, info.IsDir(), "the gitdir file must survive the update")
		})
	}
}
