package codex

import (
	"strings"

	"github.com/insajin/autopus-adk/pkg/adapter"
	"github.com/insajin/autopus-adk/pkg/config"
)

const (
	codexGeneratedConfigHeader = "# Codex configuration (auto-generated by Autopus-ADK)"
	codexUserModelMarker       = "# Autopus: user-owned Codex model settings"
)

var userOwnedCodexConfigKeys = map[string]map[string]bool{
	"": {
		"model":                   true,
		"model_reasoning_effort":  true,
		"model_reasoning_summary": true,
		"model_verbosity":         true,
	},
}

type codexModelPreservation struct {
	overrides map[string]string
	mark      bool
}

// codexModelSettingsToPreserve resolves ownership per root setting. Legacy
// managed files stay preservation-first until the user selects an explicit
// supervisor policy, which acts as the reclaim boundary for known profiles.
func codexModelSettingsToPreserve(
	existing []byte,
	oldManifest *adapter.Manifest,
	legacySupervisorPolicy bool,
) codexModelPreservation {
	content := string(existing)
	overrides := collectCodexConfigOverrides(content)
	if len(overrides) == 0 {
		return codexModelPreservation{}
	}
	if marked, ok := markedCodexModelOverrides(content, overrides); ok {
		return codexModelPreservation{overrides: marked, mark: len(marked) > 0}
	}

	_, managed := codexManifestConfigEntry(oldManifest)
	if !managed || !hasStandaloneCodexComment(content, codexGeneratedConfigHeader) {
		return codexModelPreservation{overrides: overrides, mark: true}
	}
	if legacySupervisorPolicy {
		return codexModelPreservation{overrides: overrides}
	}

	custom := selectCustomCodexModelOverrides(overrides)
	return codexModelPreservation{overrides: custom, mark: len(custom) > 0}
}

func codexManifestConfigEntry(oldManifest *adapter.Manifest) (adapter.ManifestFile, bool) {
	if oldManifest == nil {
		return adapter.ManifestFile{}, false
	}
	entry, ok := oldManifest.Files[codexConfigRelPath]
	return entry, ok
}

func selectCustomCodexModelOverrides(overrides map[string]string) map[string]string {
	custom := make(map[string]string)
	model, hasModel := overrides[".model"]
	effort, hasEffort := overrides[".model_reasoning_effort"]
	if !isKnownManagedCodexSupervisorTuple(model, hasModel, effort, hasEffort) {
		if hasModel {
			custom[".model"] = model
		}
		if hasEffort {
			custom[".model_reasoning_effort"] = effort
		}
	}
	if summary, ok := overrides[".model_reasoning_summary"]; ok && !codexStringEquals(summary, "auto") {
		custom[".model_reasoning_summary"] = summary
	}
	if verbosity, ok := overrides[".model_verbosity"]; ok && !codexStringEquals(verbosity, "medium") {
		custom[".model_verbosity"] = verbosity
	}
	return custom
}

func isKnownManagedCodexSupervisorTuple(model string, hasModel bool, effort string, hasEffort bool) bool {
	if !hasModel || !hasEffort {
		return false
	}
	modelValue, modelOK := parseCodexStringValue(model)
	effortValue, effortOK := parseCodexStringValue(effort)
	if !modelOK || !effortOK {
		return false
	}
	switch modelValue {
	case config.CodexLegacyModel:
		return effortValue == config.CodexEffortXHigh
	case config.CodexSolModel, config.CodexGPT6SolModel, config.CodexPreviousSolModel:
		return effortValue == config.CodexEffortXHigh || effortValue == config.CodexEffortUltra
	case config.CodexAstraModel:
		return effortValue == config.CodexEffortXHigh || effortValue == config.CodexEffortUltra
	default:
		return false
	}
}

// preserveUserCodexModelSettings applies only the settings whose ownership was
// resolved above while allowing all other generated config to refresh.
func preserveUserCodexModelSettings(rendered string, preservation codexModelPreservation) string {
	if len(preservation.overrides) == 0 {
		return rendered
	}

	var section string
	lines := strings.Split(rendered, "\n")
	applied := make(map[string]bool, len(preservation.overrides))
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if parsedSection, ok := parseCodexConfigSection(trimmed); ok {
			section = parsedSection
			continue
		}
		key, _, ok := parseCodexConfigAssignment(trimmed)
		if !ok || !isUserOwnedCodexConfigKey(section, key) {
			continue
		}
		overrideKey := section + "." + key
		if replacement, ok := preservation.overrides[overrideKey]; ok {
			lines[i] = replaceCodexConfigAssignmentValue(line, replacement)
			applied[overrideKey] = true
		}
	}

	var missingRoot []string
	for _, key := range []string{"model", "model_reasoning_effort", "model_reasoning_summary", "model_verbosity"} {
		overrideKey := "." + key
		if value, ok := preservation.overrides[overrideKey]; ok && !applied[overrideKey] {
			missingRoot = append(missingRoot, key+" = "+value)
		}
	}
	if len(missingRoot) > 0 {
		insertAt := len(lines)
		for i, line := range lines {
			if _, ok := parseCodexConfigSection(strings.TrimSpace(line)); ok {
				insertAt = i
				break
			}
		}
		missingRoot = append(missingRoot, "")
		updated := make([]string, 0, len(lines)+len(missingRoot))
		updated = append(updated, lines[:insertAt]...)
		updated = append(updated, missingRoot...)
		updated = append(updated, lines[insertAt:]...)
		lines = updated
	}
	if preservation.mark {
		lines = insertCodexUserModelMarker(lines, preservation.overrides)
	}
	return strings.Join(lines, "\n")
}

// insertCodexUserModelMarker places exactly one marker before the first
// user-owned assignment. mergeCodexConfig carries every comment line of the
// existing file forward, so the marker written by the previous update is
// dropped first; otherwise each update would append another copy.
func insertCodexUserModelMarker(lines []string, overrides map[string]string) []string {
	marker := formatCodexUserModelMarker(overrides)
	if marker == "" {
		return lines
	}
	lines = dropStandaloneCodexUserModelMarkers(lines)
	section := ""
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if parsedSection, ok := parseCodexConfigSection(trimmed); ok {
			section = parsedSection
			continue
		}
		key, _, ok := parseCodexConfigAssignment(trimmed)
		if ok && isUserOwnedCodexConfigKey(section, key) {
			updated := make([]string, 0, len(lines)+1)
			updated = append(updated, lines[:i]...)
			updated = append(updated, marker)
			updated = append(updated, lines[i:]...)
			return updated
		}
	}
	return lines
}

// dropStandaloneCodexUserModelMarkers removes marker comments that are real
// TOML comments. A marker inside a multiline string is user data and stays.
func dropStandaloneCodexUserModelMarkers(lines []string) []string {
	var scan codexTOMLScanState
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		if scan.skipSyntaxLine(line) {
			kept = append(kept, line)
			continue
		}
		trimmed := strings.TrimSpace(line)
		if trimmed == codexUserModelMarker || strings.HasPrefix(trimmed, codexUserModelMarker+":") {
			continue
		}
		if _, value, ok := parseCodexConfigAssignment(trimmed); ok {
			scan.observeValue(value)
		}
		kept = append(kept, line)
	}
	return kept
}

func formatCodexUserModelMarker(overrides map[string]string) string {
	var keys []string
	for _, key := range []string{"model", "model_reasoning_effort", "model_reasoning_summary", "model_verbosity"} {
		if _, ok := overrides["."+key]; ok {
			keys = append(keys, key)
		}
	}
	if len(keys) == 0 {
		return ""
	}
	return codexUserModelMarker + ": " + strings.Join(keys, ", ")
}
