package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/insajin/autopus-adk/pkg/adapter"
	"github.com/insajin/autopus-adk/pkg/config"
)

func (a *Adapter) buildUpdateTransactionPlan(
	cfg *config.HarnessConfig,
	oldManifest *adapter.Manifest,
	newFiles []adapter.FileMapping,
) (adapter.TransactionPlan, *adapter.PlatformFiles, error) {
	finalFiles := make([]adapter.FileMapping, 0, len(newFiles))
	writes := make([]adapter.TransactionWrite, 0, len(newFiles))
	var skippedPaths []string

	for _, file := range newFiles {
		action := adapter.ResolveAction(a.root, file.TargetPath, file.OverwritePolicy, oldManifest)
		if action == adapter.ActionSkip {
			skippedPaths = append(skippedPaths, file.TargetPath)
			continue
		}
		finalFiles = append(finalFiles, file)
		writes = append(writes, adapter.TransactionWrite{
			Path:    file.TargetPath,
			Content: file.Content,
			Perm:    codexFileMode(file.TargetPath),
		})
	}

	removes, err := a.buildUpdateTransactionRemoves(cfg, oldManifest, newFiles, writes)
	if err != nil {
		return adapter.TransactionPlan{}, nil, err
	}

	pf := &adapter.PlatformFiles{
		Files:    finalFiles,
		Checksum: checksum(fmt.Sprintf("%d", len(finalFiles))),
	}
	manifest := adapter.ManifestFromFiles(adapterName, filterCodexManifestFiles(cfg, pf))
	if oldManifest != nil {
		for _, path := range skippedPaths {
			if previous, ok := oldManifest.Files[path]; ok {
				manifest.Files[path] = previous
			}
		}
	}
	plan := adapter.TransactionPlan{
		Writes:   writes,
		Removes:  removes,
		Manifest: manifest,
	}
	return plan, pf, nil
}

// buildUpdateTransactionRemoves plans every deletion an update performs.
//
// Three sources feed it. The manifest diff catches any managed file
// the previous install recorded and this one no longer emits, which is the wide
// net but only exists when a manifest survives. The obsolete-surface detector
// catches a closed, hardcoded set of retired layouts regardless of the manifest,
// which is what makes a fresh clone converge: `.autopus/*-manifest.json` is
// gitignored, so a cloned workspace has generated files with no ownership record
// and a manifest-only prune is structurally blind to them — it would rewrite the
// manifest without the orphans and never see them again. The group S
// declaration (adapter.StaleCompletionHookScripts) adds the retired completion
// hook scripts that the transaction's final state no longer names, so the
// transaction that retracts their hooks.json handlers deletes them.
func (a *Adapter) buildUpdateTransactionRemoves(
	cfg *config.HarnessConfig,
	oldManifest *adapter.Manifest,
	files []adapter.FileMapping,
	writes []adapter.TransactionWrite,
) ([]adapter.TransactionRemove, error) {
	var removes []adapter.TransactionRemove
	planned := make(map[string]bool)
	add := func(remove adapter.TransactionRemove) {
		key := filepath.ToSlash(filepath.Clean(remove.Path))
		if planned[key] {
			return
		}
		planned[key] = true
		removes = append(removes, remove)
	}

	if oldManifest != nil {
		diff := adapter.BuildManifestDiff(oldManifest, files, PruneRoots())
		for _, entry := range diff.Prune {
			add(adapter.TransactionRemove{Path: entry.Path})
		}
	}
	for _, remove := range a.pluginWorkflowShimRemoves() {
		add(remove)
	}
	for _, path := range obsoleteCodexSurfacePaths(a.root, a.openCodeOwnsSharedSkills(cfg)) {
		add(adapter.TransactionRemove{Path: path, Recursive: true})
	}
	if remove, ok := a.legacyRootConfigRemove(); ok {
		add(remove)
	}
	scripts := adapter.StaleCompletionHookScripts(adapterName)
	for _, remove := range adapter.StaleCompletionScriptRemoves(a.root, scripts, writes) {
		add(remove)
	}
	return adapter.FilterUnsupportedRootGitHookRemoves(a.root, removes), nil
}

func (a *Adapter) pluginWorkflowShimRemoves() []adapter.TransactionRemove {
	removes := make([]adapter.TransactionRemove, 0, len(workflowSpecs))
	for _, spec := range workflowSpecs {
		if spec.Name == "auto" {
			continue
		}
		removes = append(removes, adapter.TransactionRemove{
			Path:      filepath.Join(".autopus", "plugins", "auto", "skills", spec.Name),
			Recursive: true,
		})
	}
	return removes
}

func (a *Adapter) legacyRootConfigRemove() (adapter.TransactionRemove, bool) {
	target := filepath.Join(a.root, "config.toml")
	data, err := os.ReadFile(target)
	if err != nil || !strings.Contains(string(data), "auto-generated by Autopus-ADK") {
		return adapter.TransactionRemove{}, false
	}
	return adapter.TransactionRemove{Path: "config.toml"}, true
}

func codexFileMode(path string) os.FileMode {
	clean := filepath.ToSlash(path)
	if adapter.IsRootGitHookPath(clean) || strings.HasSuffix(clean, ".sh") {
		return 0755
	}
	return 0644
}
