package evalregression

import (
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strconv"
	"strings"
	"testing"
	"time"
)

// harnessSignProducedAt keeps a +09:00 offset so a signer that re-renders
// the time instead of copying the report string would be caught.
const harnessSignProducedAt = "2026-10-06T21:18:22+09:00"

// harnessTestBinding is a binding digest made inside the test, never a
// committed literal (acceptance.md: B is generated by the test).
func harnessTestBinding(t *testing.T) string {
	t.Helper()
	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		t.Fatalf("binding digest: %v", err)
	}
	return hex.EncodeToString(raw)
}

func harnessTestKey(t *testing.T) (ed25519.PublicKey, ed25519.PrivateKey) {
	t.Helper()
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate test key: %v", err)
	}
	return pub, priv
}

// harnessLanePolicy holds the REQ-HR-03 attestation literals of the harness lane.
func harnessLanePolicy(binding string) EvalRegressionAttestationPolicyV2 {
	return EvalRegressionAttestationPolicyV2{
		ExpectedKeyID:     ADKHarnessEvalKeyID,
		TrustLane:         ADKHarnessEvalTrustLane,
		SourceEnvironment: "adk-harness-live",
		TargetEnvironment: "adk-release",
		SourceRevision:    binding,
		WorkspaceScope:    "autopus-adk",
	}
}

// autopusLanePolicy holds the lane literals of the Autopus gate
// (../Autopus/.github/workflows/eval-regression-gate.yml L200-203); the
// revision and workspace scope are per-run values there.
func autopusLanePolicy() EvalRegressionAttestationPolicyV2 {
	return EvalRegressionAttestationPolicyV2{
		ExpectedKeyID:     "autopus-eval-staging-to-main-2026-07",
		TrustLane:         "staging-to-main",
		SourceEnvironment: "staging",
		TargetEnvironment: "production",
		SourceRevision:    "0123456789abcdef0123456789abcdef01234567",
		WorkspaceScope:    "autopus-staging",
	}
}

func harnessSignReport(blocked bool, version, producedAt, scope string) []byte {
	reason, delta := "within_threshold", "0.05"
	if blocked {
		reason, delta = "pass_rate_regression", "-0.5"
	}
	return []byte(`{"schema_version":"eval_regression_report.v1","blocked":` + strconv.FormatBool(blocked) +
		`,"regression_delta":` + delta + `,"attributed_version":"` + version +
		`","comparison_scope":"adk-harness-golden-live","threshold_metric":"pass_rate_delta","threshold_value":-0.1,` +
		`"reason":"` + reason + `","baseline_ref":"v0.50.122","produced_at":"` + producedAt +
		`","workspace_scope":"` + scope + `","raw_payload_present":false,` +
		`"redaction_status":"body_free","retention_class":"release_evidence"}` + "\n")
}

func mustSignHarness(t *testing.T, report []byte, policy EvalRegressionAttestationPolicyV2, priv ed25519.PrivateKey) []byte {
	t.Helper()
	att, err := SignEvalRegressionAttestationV2(report, policy, priv)
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	data, err := json.Marshal(att)
	if err != nil {
		t.Fatalf("marshal attestation: %v", err)
	}
	return data
}

// strictGate runs the strict verifier and then the pure gate, the order of
// checkEvalRegressionStrict, and returns the reason and version it would print.
func strictGate(t *testing.T, report, att []byte, trusted map[string]ed25519.PublicKey, policy EvalRegressionAttestationPolicyV2, now time.Time) (string, string) {
	t.Helper()
	if reason, ok := VerifyEvalRegressionArtifactV2Strict(report, att, trusted, policy); !ok {
		return reason, ""
	}
	var decoded EvalRegressionReportV1
	dec := json.NewDecoder(bytes.NewReader(report))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&decoded); err != nil {
		t.Fatalf("a verified report must decode strictly: %v", err)
	}
	decision := EvaluateEvalRegressionGate(decoded, now, 72*time.Hour)
	return decision.Reason, decision.AttributedVersion
}

func TestSignEvalRegressionAttestationV2_HarnessLaneRoundTripsThroughTheStrictPath(t *testing.T) {
	t.Parallel()
	pub, priv := harnessTestKey(t)
	binding := harnessTestBinding(t)
	policy := harnessLanePolicy(binding)
	trusted := map[string]ed25519.PublicKey{ADKHarnessEvalKeyID: pub}
	produced, err := time.Parse(time.RFC3339, harnessSignProducedAt)
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct {
		name    string
		blocked bool
		want    string
	}{{"good", false, "ok"}, {"blocked", true, "regression_blocked"}} {
		report := harnessSignReport(tc.blocked, binding, harnessSignProducedAt, "autopus-adk")
		att := mustSignHarness(t, report, policy, priv)
		if reason, version := strictGate(t, report, att, trusted, policy, produced.Add(time.Hour)); reason != tc.want || version != binding {
			t.Fatalf("%s: got (%q, %q), want (%q, %q)", tc.name, reason, version, tc.want, binding)
		}
		if reason, version := strictGate(t, report, att, trusted, policy, produced.Add(73*time.Hour)); reason != "artifact_stale" || version != binding {
			t.Fatalf("%s 73h later: got (%q, %q), want artifact_stale for %q", tc.name, reason, version, binding)
		}
	}
	var decoded EvalRegressionAttestationV2
	if err := json.Unmarshal(mustSignHarness(t, harnessSignReport(false, binding, harnessSignProducedAt, "autopus-adk"), policy, priv), &decoded); err != nil {
		t.Fatal(err)
	}
	want := EvalRegressionAttestationV2{
		SchemaVersion: "eval_regression_attestation.v2", KeyID: ADKHarnessEvalKeyID, Algorithm: "ed25519",
		ProducedAt: harnessSignProducedAt, TrustLane: "adk-harness-eval", SourceEnvironment: "adk-harness-live",
		TargetEnvironment: "adk-release", SourceRevision: binding, WorkspaceScope: "autopus-adk",
	}
	decoded.SignatureB64, decoded.ReportSHA256 = "", ""
	if decoded != want {
		t.Fatalf("attestation context = %+v, want %+v", decoded, want)
	}
}

func TestSignEvalRegressionAttestationV2_TamperAndUnknownKeysFailClosed(t *testing.T) {
	t.Parallel()
	pub, priv := harnessTestKey(t)
	otherPub, _ := harnessTestKey(t)
	binding := harnessTestBinding(t)
	policy := harnessLanePolicy(binding)
	report := harnessSignReport(true, binding, harnessSignProducedAt, "autopus-adk")
	att := mustSignHarness(t, report, policy, priv)
	tampered := bytes.Replace(report, []byte(`"regression_delta":-0.5`), []byte(`"regression_delta":-0.4`), 1)
	if len(tampered) != len(report) || bytes.Equal(tampered, report) {
		t.Fatal("setup: the tamper must change exactly one byte")
	}
	now := time.Date(2026, 10, 6, 13, 0, 0, 0, time.UTC)
	cases := map[string]struct {
		report  []byte
		trusted map[string]ed25519.PublicKey
		want    string
	}{
		"one byte tampered":     {tampered, map[string]ed25519.PublicKey{ADKHarnessEvalKeyID: pub}, "signature_invalid"},
		"key id not trusted":    {report, map[string]ed25519.PublicKey{}, "signature_key_unknown"},
		"another key in its id": {report, map[string]ed25519.PublicKey{ADKHarnessEvalKeyID: otherPub}, "signature_invalid"},
	}
	for name, tc := range cases {
		if reason, _ := strictGate(t, tc.report, att, tc.trusted, policy, now); reason != tc.want {
			t.Fatalf("%s: reason %q, want %q", name, reason, tc.want)
		}
	}
}

func TestSignEvalRegressionAttestationV2_HarnessAndAutopusLanesRejectEachOther(t *testing.T) {
	t.Parallel()
	harnessPub, harnessPriv := harnessTestKey(t)
	autopusPub, autopusPriv := harnessTestKey(t)
	binding := harnessTestBinding(t)
	trusted := map[string]ed25519.PublicKey{ADKHarnessEvalKeyID: harnessPub, autopusLanePolicy().ExpectedKeyID: autopusPub}
	now := time.Date(2026, 10, 6, 13, 0, 0, 0, time.UTC)

	harnessReport := harnessSignReport(false, binding, harnessSignProducedAt, "autopus-adk")
	harnessAtt := mustSignHarness(t, harnessReport, harnessLanePolicy(binding), harnessPriv)
	if reason, _ := strictGate(t, harnessReport, harnessAtt, trusted, autopusLanePolicy(), now); reason != "attestation_policy_mismatch" {
		t.Fatalf("harness evidence under the Autopus policy: %q, want attestation_policy_mismatch", reason)
	}
	autopus := autopusLanePolicy()
	autopusReport := harnessSignReport(false, autopus.SourceRevision, harnessSignProducedAt, autopus.WorkspaceScope)
	autopusAtt := mustSignHarness(t, autopusReport, autopus, autopusPriv)
	if reason, _ := strictGate(t, autopusReport, autopusAtt, trusted, harnessLanePolicy(binding), now); reason != "attestation_policy_mismatch" {
		t.Fatalf("Autopus evidence under the harness policy: %q, want attestation_policy_mismatch", reason)
	}

	// A one-second produced_at difference between the report and a validly
	// signed attestation is a context mismatch. The signer cannot produce it
	// because it copies the report string, so the statement is re-signed here.
	var shifted EvalRegressionAttestationV2
	if err := json.Unmarshal(harnessAtt, &shifted); err != nil {
		t.Fatal(err)
	}
	shifted.ProducedAt = "2026-10-06T21:18:23+09:00"
	message, err := evalRegressionAttestationV2Message(shifted)
	if err != nil {
		t.Fatal(err)
	}
	shifted.SignatureB64 = base64.StdEncoding.EncodeToString(ed25519.Sign(harnessPriv, message))
	shiftedAtt, err := json.Marshal(shifted)
	if err != nil {
		t.Fatal(err)
	}
	if reason, _ := strictGate(t, harnessReport, shiftedAtt, trusted, harnessLanePolicy(binding), now); reason != "attestation_policy_mismatch" {
		t.Fatalf("produced_at one second apart: %q, want attestation_policy_mismatch", reason)
	}
}

func TestSignEvalRegressionAttestationV2_RefusesWhatTheVerifierCouldNotTrust(t *testing.T) {
	t.Parallel()
	_, priv := harnessTestKey(t)
	_, other := harnessTestKey(t)
	binding := harnessTestBinding(t)
	good := harnessSignReport(false, binding, harnessSignProducedAt, "autopus-adk")
	mixed := append(append(ed25519.PrivateKey{}, priv.Seed()...), other.Public().(ed25519.PublicKey)...)
	padded := harnessLanePolicy(binding)
	padded.TrustLane = " adk-harness-eval"
	blank := harnessLanePolicy(binding)
	blank.SourceRevision = ""
	cases := map[string]struct {
		report []byte
		policy EvalRegressionAttestationPolicyV2
		key    ed25519.PrivateKey
		want   error
	}{
		"padded context":          {good, padded, priv, ErrSignContextInvalid},
		"blank context":           {good, blank, priv, ErrSignContextInvalid},
		"seed only":               {good, harnessLanePolicy(binding), priv.Seed(), ErrSignKeyInvalid},
		"seed and foreign half":   {good, harnessLanePolicy(binding), mixed, ErrSignKeyInvalid},
		"other workspace scope":   {harnessSignReport(false, binding, harnessSignProducedAt, "autopus-primary"), harnessLanePolicy(binding), priv, ErrSignReportInvalid},
		"no produced_at":          {[]byte(`{"workspace_scope":"autopus-adk"}`), harnessLanePolicy(binding), priv, ErrSignReportInvalid},
		"padded produced_at":      {harnessSignReport(false, binding, " "+harnessSignProducedAt, "autopus-adk"), harnessLanePolicy(binding), priv, ErrSignReportInvalid},
		"malformed report":        {[]byte(`{"produced_at":`), harnessLanePolicy(binding), priv, ErrSignReportInvalid},
		"data after the document": {append(append([]byte{}, good...), `{}`...), harnessLanePolicy(binding), priv, ErrSignReportInvalid},
	}
	for name, tc := range cases {
		att, err := SignEvalRegressionAttestationV2(tc.report, tc.policy, tc.key)
		if !errors.Is(err, tc.want) {
			t.Fatalf("%s: error %v, want %v", name, err, tc.want)
		}
		if att != (EvalRegressionAttestationV2{}) {
			t.Fatalf("%s: a refused signature returned %+v", name, att)
		}
	}
}

func TestADKHarnessEvalLaneConstants_SeparateTheLaneFromAutopus(t *testing.T) {
	t.Parallel()
	if ADKHarnessEvalTrustLane != "adk-harness-eval" {
		t.Fatalf("trust lane = %q, want the REQ-HR-03 literal adk-harness-eval", ADKHarnessEvalTrustLane)
	}
	if ADKHarnessEvalKeyID == autopusLanePolicy().ExpectedKeyID || ADKHarnessEvalTrustLane == autopusLanePolicy().TrustLane {
		t.Fatal("the harness lane must not reuse the Autopus key id or trust lane")
	}
	if strings.TrimSpace(ADKHarnessEvalKeyID) != ADKHarnessEvalKeyID || !strings.HasPrefix(ADKHarnessEvalKeyID, ADKHarnessEvalTrustLane+"-") {
		t.Fatalf("key id %q must be a clean id of the %s lane", ADKHarnessEvalKeyID, ADKHarnessEvalTrustLane)
	}
}
